#
# OpenAPI Petstore
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSPetOnlineStore' -name 'StoreApi' {
    Context 'Invoke-DeleteOrder' {
        It 'Test Invoke-DeleteOrder' {
            #$TestResult = Invoke-DeleteOrder -OrderId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-Inventory' {
        It 'Test Get-Inventory' {
            #$TestResult = Get-Inventory
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OrderById' {
        It 'Test Get-OrderById' {
            #$TestResult = Get-OrderById -OrderId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-PlaceOrder' {
        It 'Test Invoke-PlaceOrder' {
            #$TestResult = Invoke-PlaceOrder -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
