#
# OpenAPI Petstore
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSPetOnlineStore' -name 'ApiResponse' {
    Context 'ApiResponse' {
        It 'Initialize-ApiResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-ApiResponse -Code "TEST_VALUE" -Type "TEST_VALUE" -Message "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
