#
# OpenAPI Petstore
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSPetOnlineStore' -name 'Category' {
    Context 'Category' {
        It 'Initialize-Category' {
            # a simple test to create an object
            #$NewObject = Initialize-Category -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType Category
            #$NewObject.property | Should -Be 0
        }
    }
}
